//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;

    public partial class File : IDALTables
    {
        public int Fid { get; set; }
        public string Fname { get; set; }
        public string Fpath { get; set; }
        public int FtypeId { get; set; }
        public int FprogramId { get; set; }

        public virtual FileType FileType { get; set; }
        public virtual Program Program { get; set; }
    }
}
