//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent : IDALTables
    {
        public string Rid { get; set; }
        public int RuserId { get; set; }
        public System.DateTime RfromDate { get; set; }
        public System.DateTime RtoDate { get; set; }
        public int Rprice { get; set; }
        public string Rpassword { get; set; }
        public bool Ractive { get; set; }
        public int RprogramId { get; set; }
        public bool Rstatus { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual User User { get; set; }
    }
}
